Allow to disable ingress creation
microcks/microcks pull request #679
Opened 2022-10-27 14:05 UTC by marsou77

I don't need an ingress to run Microcks since I use Istio on my cluster. To use this Helm chart, I need this change.

2022-11-02 15:54 UTC, marsou77 commented
Hello @lbroudoux, when can I expect this to be merged ? Thank you :)

2022-11-02 16:06 UTC, lbroudoux commented
Hi there! Yes this is of great interest: thanks a lot! I currently have some days off but will have a look at it next week.

2022-11-09 20:35 UTC, lbroudoux requested changes
Thnaks!
Looks good to me apart the naming of param that'd better be `ingresses` IMO. Also could you complete the 2 `README.md` files (basically they're the same) to include documentation on this setting?

2022-11-09 20:35 UTC, lbroudoux commented on install/kubernetes/microcks/values.yaml
> +ingress: true
I think it would be better to name it `ingresses` as it controls the generation of all the `Ingress` objects.

2022-11-09 20:56 UTC, marsou77 commented
> Thnaks! Looks good to me apart the naming of param that'd better be `ingresses` IMO. Also could you complete the 2 `README.md` files (basically they're the same) to include documentation on this setting?

Done ! Agree with Ingresses :)
For the documentation I added `appName` which was missing. Not sure about the name I put on `section`, you tell me if it sounds right

2022-11-09 21:13 UTC, lbroudoux commented
That was super fast! 😊
Time to sleep for me now but will finish it tomorrow. Thanks again,

2022-11-15 17:04 UTC, lbroudoux approved these changes
LGTM 👍

2022-11-15 17:04 UTC, merged