Code refactoring
microcks/microcks pull request #780
Opened 2023-04-06 18:25 UTC by CapnSK

### Description

- Extracted complex conditions into a method for increased readability: DispatchCriteriaHelper.java:374
- Created a method out of an operations finding task for reusability  & improved readability: RestController.java:132
- Renamed method as per semantics for better understanding its use: DocumentationController.java: 56
- Moved method computeMaxPossibleConformanceScore logic from MetricService to MessageService because of lack of cohesion
- Created SchemaValidator base abstract class with abstract validate method and OpenAPISchemaValidator and SwaggerSchemaValidator to extend the base class and implement validate method.
- Response, Request and EventMessage classes use id variable which can be kept in Message class for better maintainability
- DynamicMockRestController has certain utilities which have more to do with Json handling, extracted these methods into a nested class for better abstraction

2023-04-11 08:38 UTC, lbroudoux commented
Thanks a lot for these refactoring 👍 
Will rebase it on the `1.7.x` branch as this is where next developments are. 
It will probably take a bit of time to review everything 😉 
Do not hesitate to join GH discussions or zulip to discuss refactoring beforehand so that we can also agree on a strategy to split them and accelerate review and integration.
Thanks again!

2023-04-12 14:44 UTC, CapnSK commented
Apologies for not discussing this beforehand; thanks for considering merging this pull request.

2023-04-17 20:44 UTC, lbroudoux commented on commons/util/src/main/java/io/github/microcks/util/openapi/SchemaValidator.java
It could be nice to discuss the purpose of introducing this interface... Would it be possible to use it again for some other specs like AsyncAPI and GraphQL for example? Does it ease schema validator client usage as well? I don't see the point at the moment and I'd like to see further before applying the change.

2023-04-17 20:46 UTC, lbroudoux commented on webapp/src/main/java/io/github/microcks/service/MessageService.java
> +   public List<? extends Exchange> computeMaxPossibleConformanceScore(Service service, Operation operation){
I think the name of this method is not appropriate here... Something like `getExchangesByOperation()` would be more appropriate.

2023-04-17 20:46 UTC, lbroudoux commented on webapp/src/main/java/io/github/microcks/service/MetricsService.java
> +         List<? extends Exchange> exchanges = messageService.computeMaxPossibleConformanceScore(service, operation);
See comment on MessageService extracted method name...

2023-04-17 20:47 UTC, lbroudoux requested changes
Please let me know what you think of above comments.

2023-06-02 12:25 UTC, lbroudoux commented
HI @CapnSK! Would you still want to pursue on this one? I think some renaming is required if I remember correctly but nothing that looks too complicated. Let me know.

2023-06-13 19:36 UTC, lbroudoux commented
Shifting this one to next version as we'll not be able to handle it for 1.7.1

2023-10-10 13:45 UTC, lbroudoux commented
Hi @CapnSK!
Are you still interested in contributing this one? If you could have a look at it this week, I could integrate those into the next `1.8.0` release. Otherwise, we'll have to shift this one...
Many thanks!

2024-03-07 16:10 UTC, lbroudoux commented
It's been too long since this PR receive attention. Also, most of the code refactoring has been done apart from successive smallest  issues. Closing it as undone.

2024-03-07 16:10 UTC, closed without merging