[proposition] Use main instead of master (cultural inclu…
microcks/microcks pull request #939
Opened 2023-10-13 07:13 UTC by JulienBreux

### Description

All new projects in the Github or Gitlab world now use a `main` branch.

The idea is to make the Microcks project and its users more culturally inclusive.

- [x] Fixing Microcks for future usage of `main` branch.
- [x] Fixing relative links

2023-10-13 10:43 UTC, JulienBreux commented
Sounds good to me!

2023-10-16 13:09 UTC, lbroudoux requested changes
LGTM apart from some Java files indentation that was set to 2 spaces instead of 3. Can you please fix this?

2023-10-16 13:09 UTC, lbroudoux commented on commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java
> +  private static Logger log = LoggerFactory.getLogger(OpenAPISchemaValidator.class);
File was indented with 2 spaces instead of 3. Can you please fix this to avoid noise?

2023-10-16 13:09 UTC, lbroudoux commented on webapp/src/main/java/io/github/microcks/util/SoapMessageValidator.java
> +  private static Logger log = LoggerFactory.getLogger(SoapMessageValidator.class);
File was indented with 2 spaces instead of 3. Can you please fix this to avoid noise?

2023-10-16 13:09 UTC, lbroudoux commented on webapp/src/test/java/io/github/microcks/util/asyncapi/AsyncAPIImporterTest.java
> +  public void testSimpleAsyncAPIImportYAML() {
File was indented with 2 spaces instead of 3. Can you please fix this to avoid noise?

2023-10-16 13:48 UTC, JulienBreux commented
I use VSCode and unfortunately Java isn't correctly configured for me on my environment.
I'll probably re-open another ~changeset~ PR.

2023-10-16 13:48 UTC, closed without merging